---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/portugues/_index.md
  label: Homepage
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/portugues/blog
  label: Post
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/portugues/author
  label: Author
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Project
- type: directory
  path: exampleSite/content/portugues/project
  label: Project
  create: documents
  match: "**/*"
  templates:
  - project
- type: heading
  label: Other Pages
- type: directory
  path: exampleSite/content/portugues
  label: Other Pages
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: exampleSite/content/portugues
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Translations
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.83.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server --themesDir ../.. -D -E -F --port 8080 --bind
    0.0.0.0 --renderToDisk -d public
version: 0.83.1
