---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: this is meta description
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
