name: 'Deploy'

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: 'ubuntu-20.04'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --minify --baseURL="https://cidamo.com.br/site/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          allow_empty_commit: true
